services:
  mongo-auth:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  auth-service:
    build:
      context: ./services/auth-service
    environment:
      MONGO_URI_AUTH: mongodb://mongo-auth:27017/auth
      JWT_SECRET: dev-secret
      PORT: "5000"
    ports:
      - "5000:5000"
    depends_on:
      - mongo-auth

volumes:
  mongo_data:
